<a href="https://colab.research.google.com/github/moamitay/LMM/blob/main/classifier_huggingFace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
! pip install transformers datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 3.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 15.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 18.5 MB/s eta 0:00:00


In [ ]:
!pip install accelerate -U
# After these installations you need to press RunTime --> Interapt Session!!!
#

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.7/265.7 kB 1.9 MB/s eta 0:00:00


In [ ]:
#pip install transformers[torch]

In [ ]:
from datasets import load_dataset

dataset = load_dataset("yelp_review_full")
dataset["train"][100]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:72: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:72: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

{'label': 0,
 'text': 'My expectations for McDonalds are t rarely high. But for one to still fail so spectacularly...that takes something special!\\nThe cashier took my friends\'s order, then promptly ignored me. I had to force myself in front of a cashier who opened his register to wait on the person BEHIND me. I waited over five minutes for a gigantic order that included precisely one kid\'s meal. After watching two people who ordered after me be handed their food, I asked where mine was. The manager started yelling at the cashiers for \\"serving off their orders\\" when they didn\'t have their food. But neither cashier was anywhere near those controls, and the manager was the one serving food to customers and clearing the boards.\\nThe manager was rude when giving me my order. She didn\'t make sure that I had everything ON MY RECEIPT, and never even had the decency to apologize that I felt I was getting poor service.\\nI\'ve eaten at various McDonalds restaurants for over 30 years. 

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")


def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)


tokenized_datasets = dataset.map(tokenize_function, batched=True)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:72: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

Map:   0%|          | 0/650000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [ ]:
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(1000))
small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(1000))

In [ ]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=5)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:72: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(output_dir="drive/MyDrive/data_sets/Bert_Cola/test_trainer/")

In [ ]:
import numpy as np
from datasets import load_metric

metric = load_metric("accuracy")

<ipython-input-6-56b0b4182bac>:4: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  metric = load_metric("accuracy")
/usr/local/lib/python3.10/dist-packages/datasets/load.py:752: FutureWarning: The repository for accuracy contains custom code which must be executed to correctly load the metric. You can inspect the repository content at https://raw.githubusercontent.com/huggingface/datasets/2.16.1/metrics/accuracy/accuracy.py
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this metric from the next major release of `datasets`.
  warnings.warn(


In [ ]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [ ]:
from transformers import Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
    compute_metrics=compute_metrics,
)

In [ ]:
for i in range(2):
  trainer.train()

In [ ]:
model.save_pretrained("drive/MyDrive/data_sets/Bert_Cola/bert_hugging")

In [ ]:
predictions = trainer.predict(small_eval_dataset)
print(predictions.predictions.shape, predictions.label_ids.shape)

(1000, 5) (1000,)


In [ ]:
import numpy as np

preds = np.argmax(predictions.predictions, axis=-1)

In [ ]:
preds

array([3, 2, 0, 3, 2, 4, 1, 3, 3, 3, 1, 0, 3, 2, 2, 3, 1, 0, 2, 2, 1, 2,
       2, 1, 1, 4, 4, 1, 1, 2, 1, 3, 1, 3, 4, 4, 1, 1, 3, 4, 3, 2, 0, 1,
       3, 1, 3, 2, 3, 0, 2, 1, 3, 3, 3, 4, 0, 4, 1, 4, 1, 0, 0, 0, 3, 2,
       4, 4, 2, 4, 1, 1, 4, 3, 3, 2, 2, 1, 0, 3, 2, 4, 0, 3, 4, 3, 4, 1,
       4, 2, 3, 0, 1, 0, 3, 3, 0, 0, 2, 4, 4, 1, 1, 1, 0, 1, 3, 1, 1, 1,
       1, 3, 1, 4, 0, 3, 1, 0, 2, 1, 1, 2, 1, 0, 0, 1, 3, 1, 2, 0, 3, 3,
       2, 2, 1, 3, 4, 4, 1, 2, 1, 2, 1, 0, 3, 3, 3, 1, 3, 0, 3, 4, 0, 2,
       1, 3, 1, 3, 1, 1, 2, 0, 1, 0, 0, 1, 0, 1, 3, 4, 3, 4, 4, 2, 1, 0,
       0, 2, 1, 4, 3, 0, 1, 3, 3, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 4, 0,
       2, 3, 0, 1, 3, 4, 3, 2, 1, 1, 1, 3, 1, 1, 3, 3, 4, 1, 1, 0, 0, 2,
       1, 3, 4, 1, 1, 2, 1, 0, 3, 0, 3, 1, 4, 2, 3, 2, 2, 4, 3, 3, 1, 0,
       3, 1, 1, 2, 4, 1, 2, 1, 0, 2, 1, 4, 0, 2, 1, 3, 2, 2, 4, 4, 2, 1,
       4, 4, 4, 0, 4, 0, 2, 1, 1, 1, 3, 1, 4, 1, 0, 0, 3, 1, 0, 4, 3, 0,
       0, 4, 2, 2, 3, 4, 4, 1, 0, 1, 0, 3, 3, 4, 3,

In [ ]:
for i in range(200):
  print(small_eval_dataset["label"][i],preds[i])

2 3
4 2
1 0
4 3
3 2
4 3
2 1
3 3
2 3
3 3
0 1
0 0
3 3
2 2
2 2
1 3
3 1
1 0
2 2
2 2
1 1
2 2
3 3
1 1
1 1
3 3
4 4
0 0
0 1
2 2
2 1
2 3
1 1
3 1
4 4
0 1
0 1
1 1
3 3
2 4
0 3
2 2
0 0
0 1
3 3
0 1
3 3
2 2
3 3
0 0
1 2
1 1
3 3
3 3
4 3
4 4
1 0
4 4
1 1
3 3
1 1
0 0
0 0
1 1
4 3
1 2
4 4
3 3
2 2
4 4
1 2
0 1
3 4
3 3
4 3
1 2
2 2
1 1
0 0
4 3
4 2
4 4
2 1
3 3
3 4
1 3
4 3
0 1
4 4
2 2
3 3
0 0
0 1
0 1
3 3
4 3
0 0
0 0
1 2
4 4
4 4
0 1
0 0
1 1
1 1
0 2
4 3
2 1
2 1
1 1
1 1
4 3
0 1
4 3
0 0
3 3
2 1
0 0
4 3
4 1
4 1
2 2
0 0
0 0
0 0
1 1
3 3
0 1
2 1
0 0
3 3
2 4
2 2
2 2
0 1
3 3
4 4
3 4
0 1
1 1
0 1
1 2
0 1
0 0
4 3
3 3
3 3
1 1
3 3
0 0
3 3
4 4
0 0
2 2
1 0
3 3
1 1
3 3
1 1
3 2
1 2
0 0
2 1
0 0
1 0
1 0
0 0
0 1
3 3
3 3
3 3
3 3
3 3
1 2
1 1
0 0
0 0
2 2
3 1
3 4
3 3
1 0
1 1
3 3
4 3
0 1
1 1
1 0
2 2
2 2
1 2
3 1
0 1
2 1
1 2
1 1
4 3
0 0
2 2
4 3


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_test = small_eval_dataset["label"]
y_pred = preds

# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# Display classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Display confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.5470
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.50      0.62       220
           1       0.45      0.64      0.53       213
           2       0.52      0.51      0.51       196
           3       0.48      0.61      0.54       205
           4       0.69      0.45      0.54       166

    accuracy                           0.55      1000
   macro avg       0.59      0.54      0.55      1000
weighted avg       0.59      0.55      0.55      1000

Confusion Matrix:
[[111  99   5   4   1]
 [ 25 137  45   5   1]
 [  1  46 100  42   7]
 [  2  15  39 125  24]
 [  0   6   4  82  74]]
